name: build

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - 'UAC-Control.sln'

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Upload
    - uses: actions/upload-artifact@v3
      with:
        name: UAC-Control
        path: UAC-Control\UAC-Control\bin # or path/to/artifact
