name: .NET Core Desktop
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.401

    # Setup MSBuild.exe
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Setup NuGet
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'

    # NuGet restore
    - name: NuGet restore
      run: nuget restore
      
    # Build
    - name: Build the solution
      run: msbuild /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
      
    # Upload bin directory
    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: ${{ success() }}
      with:
        name: UAC-Control
        path: D:\a\UAC-Control\UAC-Control\UAC-Control\
