permissions:
  contents: write
name: test
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: lspath
      id: lspath
      run: |
        ls
        pwd
      
    - name: gettag
      id: version
      uses: ashley-taylor/read-json-property-action@v1.1
      with:
          path: D:\a\UAC-Control\UAC-Control\UAC-Control.deps.json
          property: targets
          
    - name: Maketags
      id: tag
      run: |
        '${{steps.version.outputs.value}}' -match 'UAC-Control/\d{1,3}.\d{1,3}.\d{1,3}' 
        echo '$matches.0'
        echo '$matches.0'>> $GITHUB_OUTPUT
    - name: echoversion
      id: echo
      run: |
       echo '${{steps.tag.outputs.value}}'
      
